### ISSUE TITLE
Controller generator imports into module file incorrectly

### ISSUE THREAD

**Issue by Mark-McCracken** [ThomRick/nest-cli#1]
Hey,
when I use
```nest generate component directory/web-scraping-custom```
a few things are happening that shouldn't.
1. The name is taken literally, this should probably be slightly altered, I'd say anything after a hyphen should be capitalised, first letter should be capitalised, then hyphens removed. This should then be used throughout, to generate a component by the name WebScrapingCustomController.
2. The import statement added to the module, it needs quotes around the __DIRNAME__, and it needs to have the file extension removed. Currently I'm getting
```import {web-scraping-customController} from src/app/modules/web-scraping-custom/web-scraping-custom.controller.ts``` (or something similar, don't know about the actual directory used).
Obviously the hyphens cause issues, but if that's resolved, it should be
```import {WebScrapingCustomComponent} from "src/app/modules/web-scraping-custom/web-scraping-custom.controller"```
The .ts extension might stop it from working when it gets compiled and it doesn't need the extension anyway.

Hope this helps, let me know if there's anything I can do to lend a hand

**Comment by ThomRick** [comment]
Hey @Mark-McCracken !
Thanks for the feedback

1. In fact the bridge case is not managed in the naming but it's in the pipe ;-)

2. I'll change the generate command management for the next version. The user will define the asset name and a kind of module path to generate it. Otherwise the extension is a bug that will be fixed soon.

Thanks again

**Comment by ThomRick** [comment]
Hey @Mark-McCracken !

All the issues should be fixed in the v1.5.0
