### ISSUE TITLE
I can't nest new project

### ISSUE THREAD

**Issue by m24927605** [ThomRick/nest-cli#4]
`nest new project`,It will be failed.
the error message:
`Command failed: git clone https://github.com/ThomRick/nest-typescript-starter.git test1205
Cloning into 'test1205'...
remote: Repository not found.
fatal: repository 'https://github.com/ThomRick/nest-typescript-starter.git/' not found`

I found that github url(https://github.com/ThomRick/nest-typescript-starter.git/) is gone.
Is there any problem?

**Comment by ThomRick** [comment]
woops cleaning error
it will be fixed very soon

**Comment by ThomRick** [comment]
It should be ok now

**Comment by m24927605** [comment]
Thank you,it's work.
